CC = gcc
MATAMAZOM_OBJS = amount_set.o matamazom.o matamazom_print.o matamazom_main.o matamazom_tests.o
MATAMAZOM_EXEC = matamazom
AS_OBJS = amount_set.o amount_set_tests.o amount_set_main.o
AS_EXEC = amount_set
DEBUG_FLAG = -g
COMP_FLAG = -std=c99 -Wall -Werror
SERVER_FLAGS = -L. -lm -lmtm

$(MATAMAZOM_EXEC) : $(MATAMAZOM_OBJS)
	$(CC) $(DEBUG_FLAG) $(MATAMAZOM_OBJS) $(SERVER_FLAGS) -o $@
amount_set.o: amount_set.c amount_set.h
	$(CC) -c $(DEBUG_FLAG) $(COMP_FLAG) $*.c
matamazom.o: matamazom.c matamazom.h list.h amount_set.h matamazom_print.h
	$(CC) -c $(DEBUG_FLAG) $(COMP_FLAG) $*.c
matamazom_print.o: matamazom_print.c matamazom_print.h
	$(CC) -c $(DEBUG_FLAG) $(COMP_FLAG) $*.c
matamazom_main.o: tests/matamazom_main.c tests/matamazom_tests.h tests/test_utilities.h
	$(CC) -c $(DEBUG_FLAG) $(COMP_FLAG) tests/$*.c
matamazom_tests.o: tests/matamazom_tests.c tests/matamazom_tests.h tests/../matamazom.h tests/test_utilities.h
	$(CC) -c $(DEBUG_FLAG) $(COMP_FLAG) tests/$*.c
	
$(AS_EXEC) : $(AS_OBJS)
	$(CC) $(DEBUG_FLAG) $(AS_OBJS) -o $@
amount_set_tests.o: tests/amount_set_tests.c amount_set.h tests/amount_set_tests.h tests/test_utilities.h
	$(CC) -c $(DEBUG_FLAG) $(COMP_FLAG) tests/$*.c
amount_set_main.o: tests/amount_set_main.c tests/test_utilities.h tests/amount_set_tests.h
	$(CC) -c $(DEBUG_FLAG) $(COMP_FLAG) tests/$*.c
 
clean:
	rm -f $(MATAMAZOM_OBJS) $(MATAMAZOM_EXEC) $(AS_OBJS) $(AS_EXEC)